server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-order

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME:order_management_db}
    username: ${POSTGRES_USERNAME:order_management}
    password: ${POSTGRES_PASSWORD:order_management}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: ${SHOW_SQL:true}
      open-in-view: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_NAME:order_management_db}
      auto-index-creation: true

  flyway:
    enable: true
    baseline_on_migrate: false

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    max_retry: 3
    queues:
      update_order:
        queue: order_management_orders_processed_payment_queue
        retry_queue: order_management_orders_processed_payment_retry_queue
        dead_queue: order_management_orders_processed_payment_dead_queue
    exchanges:
      order_management_events: order_management_events
    routing_keys:
      created_order_routing_key: created_order_routing_key
      processed_payment_routing_key: processed_payment_routing_key
