server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-order

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME:msorderdb}
    username: ${POSTGRES_USERNAME:MS_ORDERS}
    password: ${POSTGRES_PASSWORD:MS_ORDERS}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: ${SHOW_SQL:true}
      open-in-view: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_NAME:msordermongodb}
      auto-index-creation: true

  flyway:
    enable: true
    baseline_on_migrate: false

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    max_retry: 3
    queues:
      update_order:
        queue: update_order_queue
        retry_queue: update_order_retry_queue
        dead_queue: update_order_dead_queue
    exchanges:
      created_order_exchange: created_order_exchange
      update_order_exchange: update_order_exchange
    routing_keys:
      created_order_routing_key: created_order_routing_key
      update_order_routing_key: update_order_routing_key
