server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-order

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME:msorderdb}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: ${SHOW_SQL:true}
      open-in-view: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_NAME:msordermongodb}
      auto-index-creation: true

  flyway:
    enable: true
    baseline_on_migrate: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mq:
  queues:
    create_order_queue: create_order_queue
    update_order_queue: update_order_queue
  exchanges:
    order_exchange: order_exchange
  routing-keys:
    order_routing_key: order_routing_key
