server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-order

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME:msorderdb}
    username: ${POSTGRES_USERNAME:MS_ORDERS}
    password: ${POSTGRES_PASSWORD:MS_ORDERS}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: ${SHOW_SQL:true}
      open-in-view: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_NAME:msordermongodb}
      auto-index-creation: true

  flyway:
    enable: true
    baseline_on_migrate: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    max_retry: ${RABBITMQ_RETRY_COUNT:3}
    queues:
      update_order:
        queue: ${RABBITMQ_QUEUE:update_order_queue}
        retry_queue: ${RABBITMQ_RETRY_QUEUE:update_order_retry_queue}
        dead_queue: ${RABBITMQ_DEAD_QUEUE:update_order_dead_queue}
    exchanges:
      created_order_exchange: ${RABBITMQ_CREATED_EXCHANGE:created_order_exchange}
      update_order_exchange: ${RABBITMQ_UPDATE_EXCHANGE:update_order_exchange}
    routing_keys:
      created_order_routing_key: ${RABBITMQ_CREATED_ROUTING_KEY:created_order_routing_key}
      update_order_routing_key: ${RABBITMQ_UPDATE_ROUTING_KEY:update_order_routing_key}
